apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow-admission-webhook
  namespace: {{ .Values.namespaces.project }}
spec:
  interval: {{ .Values.kustomizations.intervals.default }}
  timeout: {{ .Values.kustomizations.timeouts.medium }}
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  path: ./apps/admission-webhook/upstream/overlays/cert-manager
  targetNamespace: {{ .Values.namespaces.kubeflow }}
  dependsOn:
    - name: kubeflow-cert-manager-issuer
    - name: kubeflow-istio-resources
