{{- if .Values.enable.notebooks }}
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow-notebook-controller
  namespace: {{ .Values.namespaces.project }}
spec:
  interval: {{ .Values.kustomizations.intervals.default }}
  timeout: {{ .Values.kustomizations.timeouts.medium }}
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  path: ./apps/jupyter/notebook-controller/upstream/overlays/kubeflow
  targetNamespace: {{ .Values.namespaces.kubeflow }}
  dependsOn:
    - name: kubeflow-admission-webhook
    - name: kubeflow-roles
{{- end }}
