{{- if .Values.dex.copySecretsFromProject }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-copier
  namespace: {{ .Values.namespaces.project }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: {{ .Values.namespaces.project }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-copier-reader
  namespace: {{ .Values.namespaces.project }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: secret-copier
  namespace: {{ .Values.namespaces.project }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-writer
  namespace: {{ .Values.namespaces.auth }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-copier-writer
  namespace: {{ .Values.namespaces.auth }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-writer
subjects:
- kind: ServiceAccount
  name: secret-copier
  namespace: {{ .Values.namespaces.project }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-dex-secrets
  namespace: {{ .Values.namespaces.project }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: copy-dex-secrets
    spec:
      serviceAccountName: secret-copier
      restartPolicy: OnFailure
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          set -e
          SECRET_NAME="{{ .Values.namespaces.project }}"
          echo "Copying secret $SECRET_NAME from {{ .Values.namespaces.project }} to {{ .Values.namespaces.auth }}"
          
          # Get the secret from source namespace
          kubectl get secret $SECRET_NAME -n {{ .Values.namespaces.project }} -o json | \
            jq '{apiVersion, kind, metadata: {name: .metadata.name}, type, data}' \
            kubectl apply -n {{ .Values.namespaces.auth }} -f -
          
          echo "Secret $SECRET_NAME copied successfully"
{{- end }}