{{- if .Values.enable.kserve  }}
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow-kserve-models-web-app
  namespace: {{ .Values.namespaces.project }}
spec:
  interval: {{ .Values.kustomizations.intervals.default }}
  timeout: {{ .Values.kustomizations.timeouts.default }}
  prune: true
  wait: true
  validation: client
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  path: ./apps/kserve/models-web-app/overlays/kubeflow
  targetNamespace: {{ .Values.namespaces.kubeflow }}
  dependsOn:
    - name: kubeflow-kserve
    - name: kubeflow-istio-resources  
{{- end }}