{{- $nsCert := .Values.namespaces.certManager -}}
{{- $nsIstio := .Values.namespaces.istioSystem -}}
{{- $nsKnative := .Values.namespaces.knative -}}
{{- $nsKF := .Values.namespaces.kubeflow -}}
{{- $nsoap := .Values.namespaces.oauth2proxy -}}

{{- if not (lookup "v1" "Namespace" "" $nsCert) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $nsCert }}
---
{{- end }}

{{- if not (lookup "v1" "Namespace" "" $nsIstio) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $nsIstio }}
---
{{- end }}

{{- if not (lookup "v1" "Namespace" "" $nsKnative) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $nsKnative }}
---
{{- end }}

{{- if not (lookup "v1" "Namespace" "" $nsKF) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $nsKF }}
{{- end }}
---
{{- if not (lookup "v1" "Namespace" "" $nsoap) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $nsoap }}
{{- end }}
