{{- if .Values.enable.certManager }}
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow-cert-manager-base
  namespace: {{ .Values.namespaces.project }}
spec:
  interval: {{ .Values.kustomizations.intervals.default }}
  timeout: {{ .Values.kustomizations.timeouts.short }}
  prune: true
  wait: true
  force: false
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  path: ./common/cert-manager/base
  targetNamespace: {{ .Values.namespaces.certManager }}

  # 👇 Parchea los Deployments para que la leader election use el ns "cert-manager"
  patches:
    # cert-manager controller
    - target:
        group: apps
        version: v1
        kind: Deployment
        name: cert-manager
        namespace: {{ .Values.namespaces.certManager }}
      patch: |
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --leader-election-namespace={{ .Values.namespaces.certManager }}
    # cainjector
    - target:
        group: apps
        version: v1
        kind: Deployment
        name: cert-manager-cainjector
        namespace: {{ .Values.namespaces.certManager }}
      patch: |
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --leader-election-namespace={{ .Values.namespaces.certManager }}
{{- end }}