{{- if .Values.enable.certManager }}
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow-cert-manager-base
  namespace: {{ .Values.namespaces.project }}
spec:
  interval: {{ .Values.kustomizations.intervals.default }}
  timeout: {{ .Values.kustomizations.timeouts.short }}
  prune: true
  wait: true
  force: false
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  path: ./common/cert-manager/base
  targetNamespace: {{ .Values.namespaces.certManager }}
{{- end }}
