{{- if and .Values.enable.knative .Values.enable.istio }}
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow-knative-serving
  namespace: {{ .Values.namespaces.project }}
spec:
  interval: {{ .Values.kustomizations.intervals.default }}
  timeout: {{ .Values.kustomizations.timeouts.medium }}
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  path: ./common/knative/knative-serving/overlays/gateways
  targetNamespace: {{ .Values.namespaces.knative }}
  dependsOn:
    - name: kubeflow-istio-install
    - name: kubeflow-cluster-local-gateway
{{- end }}
