{{- if and .Values.enable.kserve .Values.enable.knative }}
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow-kserve
  namespace: {{ .Values.namespaces.project }}
spec:
  interval: {{ .Values.kustomizations.intervals.default }}
  timeout: {{ .Values.kustomizations.timeouts.long }}
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  path: ./apps/kserve/kserve
  targetNamespace: {{ .Values.namespaces.kubeflow }}
  dependsOn:
    - name: kubeflow-knative-serving
    - name: kubeflow-istio-resources
{{- end }}
